server:
  port: 9010
spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL1},${KAFKA_URL2},${KAFKA_URL3}
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: auth-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    listener:
      ack-mode: record




  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=seoul
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



  sql:
    init:
      mode: never
regex:
  email: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  password: '^(?=.*[A-Za-z])(?=.*\d).{8,}$'



email:
  code:
    prefix: 'email'
    length: 6
    expire:
      time: 290
security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
  aes:
    encryption-key: default-aes-encryption-key-change-in-production

oauth:
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me
  apple:
    issuer: https://appleid.apple.com



